script: |
            sudo mkdir -p /data/cicd-demo
            sudo chown sysadmin:admin /data/cicd-demo
            cd /data/cicd-demo
            if [ ! -d ".git" ]; then
              git clone https://github.com/prathmeshkamble504-ui/CICD-pipeline-demo.git .
              git checkout ${{ github.ref_name }}
            else
              git fetch origin
              git checkout ${{ github.ref_name }}
              git pull origin ${{ github.ref_name }}
            fi
            python3 app.py