name: Deploy to UAT Server

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo mkdir -p /data/cicd-demo
            sudo chown sysadmin:admin /data/cicd-demo
            cd /data/cicd-demo
            if [ ! -d ".git" ]; then
              git clone https://github.com/prathmeshkamble504-ui/CICD-pipeline-demo.git .
              git checkout feature/deploy
            else
              git fetch origin
              git checkout feature/deploy
              git pull origin feature/deploy
            fi
            python3 app.py